// frontend/src/views/Signup.vue
<template>
    <div class="flex items-center justify-center h-screen bg-gray-900">
        <div class="w-full max-w-xs">
            <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                <h1 class="text-2xl font-bold mb-4 text-gray-700 text-center">Cadastro de Usuário</h1>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">
                        Nome
                    </label>
                    <input v-model="formData.name"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="name" type="text" placeholder="Name">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="age">
                        Idade
                    </label>
                    <input v-model="formData.age"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="age" type="number" placeholder="Age">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                        Email
                    </label>
                    <input v-model="formData.email"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                        id="email" type="email" placeholder="Email">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                        Senha
                    </label>
                    <input v-model="formData.password"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                        id="password" type="password" placeholder="Password">
                </div>

                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="isAdmin">
                        Admin(Apenas para testes, em um sistema real, não teria essa opção.)
                    </label>
                    <input v-model="formData.isAdmin" type="checkbox" id="isAdmin">
                </div>

                <div class="flex justify-center">
                    <button @click.prevent="submitForm"
                        class="bg-blue-600 hover:bg-blue-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                        type="button">
                        Cadastrar
                    </button>
                </div>

                <router-link to="/entrar" class="block text-center text-blue-600 text-sm mt-2 hover:text-blue-800">
                    Já possui uma conta? Clique aqui.
                </router-link>
            </form>
            <p class="text-center text-gray-500 text-xs">
                &copy;2023 - @lsprgabriel
            </p>
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            formData: {
                name: '',
                age: null,
                email: '',
                password: '',
                isAdmin: false,
            },
        };
    },
    methods: {
        // POST Request to create a new user localhost:3000/api/signup
        async submitForm() {
            try {
                await fetch('http://127.0.0.1:3000/api/signup', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(this.formData),
                });
                this.$router.push('/entrar');
            } catch (error) {
                console.log(error);
            }
        },
    },
};
</script>

// frontend/src/Pages/Signup.tsx
import React, { useState } from "react";
import Modal from "../Components/modals/SuccessModal";

export default function SignupPage() {
    const [showModal, setShowModal] = useState(false);

    onsubmit = async (event: any) => {
        event.preventDefault();
        const { name, age, email, password, isAdmin } = event.target.elements;
        const user = {
            name: name.value,
            age: Number(age.value),
            email: email.value,
            password: password.value,
            isAdmin: JSON.parse(isAdmin.value.toLowerCase())
        };
        await fetch('http://localhost:3000/api/signup', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(user),
        })
            .then((response) => response.json())
            .then((data) => {
                // Eu sei que essa é uma forma bem terrível de fazer isso, mas o foco aqui é o Backend.
                if(data.message.includes('existe')) {
                    alert(`O email ${email.value} já está cadastrado! Tente outro.`);
                    return;
                } else if (data.message.includes('sucesso')) {
                    alert('Usuário cadastrado com sucesso! Clique em OK para ser redirecionado.');
                    sessionStorage.setItem('token', data.data.access_token);
                    setTimeout(() => {
                        window.location.href = '/dashboard';
                    }, 2000);
                    return;
                }
            })
            .catch((error) => {
                console.error('Error:', error);
            });
        // setShowModal(true);
        // setTimeout(() => {
        //     window.location.href = '/dashboard';
        // }, 2000);
    };
    return (
        <div className="min-h-screen flex items-center justify-center">
            <div className="max-w-lg w-full">
                <h1 className="text-3xl font-bold mb-6 text-center">Cadastro de usuário</h1>
                <form className="w-full max-w-lg">
                    <div className="flex flex-wrap mx-2 mb-6">
                        <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                            <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="name">
                                Nome
                            </label>
                            <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="name" type="text" placeholder="John Doe" />
                        </div>
                        <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                            <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="age">
                                Idade
                            </label>
                            <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="age" type="number" placeholder="30" />
                        </div>
                    </div>
                    <div className="flex flex-wrap mx-2 mb-6">
                        <div className="w-full px-3">
                            <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="email">
                                Email
                            </label>
                            <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="email" type="email" placeholder="john.doe@example.com" />
                        </div>
                    </div>
                    <div className="flex flex-wrap mx-2 mb-6">
                        <div className="w-full px-3">
                            <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="password">
                                Senha
                            </label>
                            <input className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="password" type="password" placeholder="*********" />
                        </div>
                    </div>
                    <div className="flex flex-wrap mx-2 mb-2">
                        <div className="w-full px-3">
                            <label className="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" htmlFor="isAdmin">
                                É administrador?
                            </label>
                            <select className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="isAdmin">
                                <option value="false">Não</option>
                                <option value="true">Sim</option>
                            </select>
                        </div>
                    </div>
                    <div className="flex items-center justify-between mx-5 mt-8">
                        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                            Cadastrar
                        </button>
                        <a className="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="/entrar">
                            Já possui uma conta?
                        </a>
                    </div>
                </form>
            </div>
            {showModal && <Modal setOpenModal={setShowModal} />}
        </div>
    );
}
